from __future__ import annotations

from finpipe.catalog.models import HealthProbeCatalogEntry, ProviderCatalogEntry

_PROBE_ACTIONS: dict[str, str] = {
    "equity.yahoo": "Fetch metadata for health.probe_symbol (default SPY)",
    "equity.alpha_vantage": "Fetch metadata for probe_symbol via Alpha Vantage",
    "options.massive": "Fetch one-row options snapshot for probe_symbol",
    "options.yahoo": "Fetch one-row Yahoo options snapshot for probe_symbol",
    "macro.fred": "Fetch 7-day DGS10 series from FRED",
    "intel.google_news": "Fetch one news headline for probe_symbol",
    "intel.stocktwits": "Fetch one StockTwits post for probe_symbol",
    "intel.reddit": "Fetch one Reddit post for probe_symbol",
    "screener.yahoo_trending": "Call Yahoo trending screener",
    "screener.yahoo_predefined": "Call Yahoo day_gainers predefined screener (limit 5)",
    "screener.finviz": "Call Finviz ta_topgainers filter",
    "screener.tradingview": "Call TradingView scanner with limit=1",
    "llm.groq": "Call Groq models.list API",
    "llm.gemini": "Call Gemini models.list API",
    "llm.nvidia": "Call NVIDIA NIM models.list API",
}

PROVIDER_CATALOG: tuple[ProviderCatalogEntry, ...] = (
    ProviderCatalogEntry(
        provider_id="yahoo",
        capability="equity",
        label="Yahoo Finance (equity)",
        description=(
            "Historical OHLCV, spot price, company metadata, "
            "and financial statements via yfinance."
        ),
        returns="TickerMetadata, DataFrame (OHLCV), float spot price, dict financials",
        settings_path="providers.yahoo",
        api_surface="client.equity.* (routed via routing.equity_primary/fallback)",
        health_probe_key="equity.yahoo",
    ),
    ProviderCatalogEntry(
        provider_id="yahoo",
        capability="options",
        label="Yahoo Finance (options)",
        description="Options chain and snapshot data via yfinance.",
        returns="OptionChain, DataFrame options snapshot",
        settings_path="providers.yahoo",
        api_surface="client.options.* / client.equity.get_options_chain",
        health_probe_key="options.yahoo",
    ),
    ProviderCatalogEntry(
        provider_id="alpha_vantage",
        capability="equity",
        label="Alpha Vantage",
        description="REST fallback for daily bars and company overview.",
        returns="TickerMetadata, DataFrame (OHLCV), float spot price",
        settings_path="providers.alpha_vantage",
        api_surface="client.equity.* (routing.equity_fallback)",
        health_probe_key="equity.alpha_vantage",
    ),
    ProviderCatalogEntry(
        provider_id="massive",
        capability="options",
        label="Massive",
        description="Primary options chain, snapshots, historical aggs, and S3 flatfiles.",
        returns="OptionChain, DataFrame snapshot, list contract dicts",
        settings_path="providers.massive",
        api_surface="client.options.*",
        health_probe_key="options.massive",
    ),
    ProviderCatalogEntry(
        provider_id="fred",
        capability="macro",
        label="FRED",
        description="Federal Reserve economic time series (e.g. DGS10 risk-free rate).",
        returns="DataFrame macro series",
        settings_path="providers.fred",
        api_surface="client.fred.get_macro_series / client.macro.*",
        health_probe_key="macro.fred",
    ),
    ProviderCatalogEntry(
        provider_id="google_news",
        capability="intel",
        label="Google News RSS",
        description="Ticker or market news headlines from Google News RSS.",
        returns="list[NewsArticle]",
        settings_path="providers.sentiment.sources.google_news",
        api_surface="client.intel.get_news",
        health_probe_key="intel.google_news",
    ),
    ProviderCatalogEntry(
        provider_id="stocktwits",
        capability="intel",
        label="StockTwits",
        description="Social microblog messages and sentiment for a symbol.",
        returns="list[SocialPost] (kind=microblog)",
        settings_path="providers.sentiment.sources.stocktwits",
        api_surface="client.intel.get_social_posts(kind=microblog)",
        health_probe_key="intel.stocktwits",
    ),
    ProviderCatalogEntry(
        provider_id="reddit",
        capability="intel",
        label="Reddit",
        description="Forum posts from finance subreddits for a symbol.",
        returns="list[SocialPost] (kind=forum)",
        settings_path="providers.sentiment.sources.reddit",
        api_surface="client.intel.get_social_posts(kind=forum)",
        health_probe_key="intel.reddit",
    ),
    ProviderCatalogEntry(
        provider_id="yahoo_trending",
        capability="screener",
        label="Yahoo trending",
        description="Currently trending US equity tickers from Yahoo Finance HTTP screener.",
        returns="list[str] ticker symbols",
        settings_path="providers.screener.sources.yahoo_trending",
        api_surface="client.screener.get_trending",
        health_probe_key="screener.yahoo_trending",
    ),
    ProviderCatalogEntry(
        provider_id="yahoo_predefined",
        capability="screener",
        label="Yahoo predefined screeners",
        description="Saved Yahoo screeners (day gainers/losers, most actives).",
        returns="list[str] ticker symbols",
        settings_path="providers.screener.sources.yahoo_predefined",
        api_surface="client.screener.get_predefined",
        health_probe_key="screener.yahoo_predefined",
    ),
    ProviderCatalogEntry(
        provider_id="finviz",
        capability="screener",
        label="Finviz screener",
        description="Fundamental/technical Finviz screener filter lists.",
        returns="list[str] ticker symbols",
        settings_path="providers.screener.sources.finviz",
        api_surface="client.screener.get_fundamental",
        health_probe_key="screener.finviz",
    ),
    ProviderCatalogEntry(
        provider_id="tradingview",
        capability="screener",
        label="TradingView scanner",
        description="TradingView America scanner POST with custom criteria.",
        returns="list[str] ticker symbols",
        settings_path="providers.screener.sources.tradingview",
        api_surface="client.screener.run_tradingview",
        health_probe_key="screener.tradingview",
    ),
    ProviderCatalogEntry(
        provider_id="groq",
        capability="llm",
        label="Groq",
        description="Groq chat completions API.",
        returns="LLMResponse text; list[str] model ids",
        settings_path="providers.groq",
        api_surface="client.groq.generate_response / client.llm.*",
        health_probe_key="llm.groq",
    ),
    ProviderCatalogEntry(
        provider_id="gemini",
        capability="llm",
        label="Gemini",
        description="Google Gemini generateContent API.",
        returns="LLMResponse text; list[str] model ids",
        settings_path="providers.gemini",
        api_surface="client.gemini.generate_response / client.llm.*",
        health_probe_key="llm.gemini",
    ),
    ProviderCatalogEntry(
        provider_id="nvidia",
        capability="llm",
        label="NVIDIA NIM",
        description="NVIDIA build.nvidia.com chat completions API (OpenAI-compatible).",
        returns="LLMResponse text; list[str] model ids",
        settings_path="providers.nvidia",
        api_surface="client.nvidia.generate_response / client.llm.*",
        health_probe_key="llm.nvidia",
    ),
)

PROBE_CATALOG: tuple[HealthProbeCatalogEntry, ...] = tuple(
    HealthProbeCatalogEntry(
        key=provider.health_probe_key,
        capability=provider.capability,
        provider_id=provider.provider_id,
        label=provider.label,
        description=provider.description,
        returns=provider.returns,
        probe_action=_PROBE_ACTIONS[provider.health_probe_key],
        settings_path=provider.settings_path,
    )
    for provider in PROVIDER_CATALOG
    if provider.health_probe_key is not None
)
